#!/bin/bash


set -u

print_usage(){
	echo "usage: psping [-c repetitions] [-t timeout] [-u  username] exe-name"
}

if [[ $# -eq 0 ]] ; then
   print_usage
   exit 1
fi

max_counts=0
timeout=1
user_name=""


while getopts :c:t:u: flag; do
	case $flag in
		c) max_counts=$OPTARG;;
		t) timeout="$OPTARG";;
		u) user_name="$OPTARG";;
	
	esac
done


command="${@: -1}"

if [ -z "$user_name" ]
then
  user="any user"
else
  user="user ‘$user_name’"
fi
 
counter=0
echo "Pinging ‘$command’ for $user"

while [ -z "$user_name" ]
do
  pscount=$(ps aux |awk '{print $1, $11}' | grep -w "$command" | wc -l)
  echo "$command: $pscount instance(s)..." 
  ((counter=counter+1))
  if [ "$counter" =  "$max_counts" ]
  then
    exit 0
  fi

  sleep $timeout
done

while [ ! -z "$user_name" ]
do
  pscount=$(ps -C "$command" -o user= | grep -w "$user_name" | wc -l)
  echo "$command: $pscount instance(s)..." 
  ((counter=counter+1))
  if [ "$counter" =  "$max_counts" ]
  then
    exit 0
  fi

  sleep $timeout
done

